const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { join } = require("node:path");
const test = require("node:test");

const source = readFileSync(join(__dirname, "../app/scheduling/page.tsx"), "utf8");

test("showtime creation retains stable retry identities", () => {
  assert.match(source, /showtimeAttemptRef = useRef/);
  assert.match(source, /updateShowtimeAttemptRef = useRef/);
  assert.match(source, /saleStatusAttemptRef = useRef/);
  assert.match(source, /quickShowtimeAttemptRef = useRef/);
  assert.match(source, /duplicateDayAttemptRef = useRef/);
  assert.match(source, /removeShowtimeAttemptRef = useRef/);
  assert.match(source, /moveShowtimeAttemptRef = useRef/);
  assert.match(source, /groupMoveAttemptRef = useRef/);
  assert.match(source, /undoMoveAttemptRef = useRef/);
  assert.match(source, /schedulePlanAttemptRef = useRef/);
  assert.match(source, /duplicatePlanAttemptRef = useRef/);
  assert.match(source, /addPlanShowtimeAttemptRef = useRef/);
  assert.match(source, /removePlanShowtimeAttemptRef = useRef/);
  assert.match(source, /updatePlanShowtimeAttemptRef = useRef/);
  assert.match(source, /renamePlanAttemptRef = useRef/);
  assert.match(source, /deletePlanAttemptRef = useRef/);
  assert.match(source, /publishPlanAttemptRef = useRef/);
  assert.match(source, /"Idempotency-Key": showtimeAttemptRef\.current!/);
  assert.match(source, /"Idempotency-Key": updateShowtimeAttemptRef\.current!/);
  assert.match(source, /"Idempotency-Key": saleStatusAttemptRef\.current\.requestId/);
  assert.match(source, /"If-Unmodified-Since": editingShowtimeUpdatedAt/);
  assert.match(source, /"Idempotency-Key": quickShowtimeAttemptRef\.current\.requestId/);
  assert.match(source, /"Idempotency-Key": duplicateDayAttemptRef\.current\.requestId/);
  assert.match(source, /"Idempotency-Key": removeShowtimeAttemptRef\.current!\.requestId/);
  assert.match(source, /"Idempotency-Key": moveShowtimeAttemptRef\.current\.requestId/);
  assert.match(source, /"Idempotency-Key": groupMoveAttemptRef\.current\.requestId/);
  assert.match(source, /"Idempotency-Key": undoMoveAttemptRef\.current\.requestId/);
  assert.match(source, /"Idempotency-Key": schedulePlanAttemptRef\.current\.requestId/);
  assert.match(source, /"Idempotency-Key": duplicatePlanAttemptRef\.current\.requestId/);
  assert.match(source, /"Idempotency-Key": addPlanShowtimeAttemptRef\.current\.requestId/);
  assert.match(source, /"Idempotency-Key": removePlanShowtimeAttemptRef\.current!\.requestId/);
  assert.match(source, /"Idempotency-Key": updatePlanShowtimeAttemptRef\.current!\.requestId/);
  assert.match(source, /"Idempotency-Key": renamePlanAttemptRef\.current!\.requestId/);
  assert.match(source, /"Idempotency-Key": deletePlanAttemptRef\.current!\.requestId/);
  assert.match(source, /"Idempotency-Key": publishPlanAttemptRef\.current!\.requestId/);
});
