ALTER TYPE "MovieArtworkPosition" ADD VALUE IF NOT EXISTS 'TOP_LEFT';
ALTER TYPE "MovieArtworkPosition" ADD VALUE IF NOT EXISTS 'TOP_RIGHT';
ALTER TYPE "MovieArtworkPosition" ADD VALUE IF NOT EXISTS 'CENTER_LEFT';
ALTER TYPE "MovieArtworkPosition" ADD VALUE IF NOT EXISTS 'CENTER_RIGHT';
ALTER TYPE "MovieArtworkPosition" ADD VALUE IF NOT EXISTS 'BOTTOM_LEFT';
ALTER TYPE "MovieArtworkPosition" ADD VALUE IF NOT EXISTS 'BOTTOM_RIGHT';
