"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { apiFetch, ApiRequestError } from "../lib/api-client";
import { loadStripeScript } from "../lib/stripe-loader";

type Plan = { id: string; name: string; description: string | null; priceCents: number; durationMonths: number; benefits: unknown };
type Config = { locationId: string; organizationName: string; currency: string; plans: Plan[]; payment: { ready: boolean; publishableKey: string | null; connectedAccountId: string | null } };
type Checkout = { checkoutId: string; planName: string; amountCents: number; currency: string; memberName: string; memberEmail: string; payment: { status: string; clientSecret?: string } };
type Confirmation = { membershipId: string; membershipNumber: string; expiresAt: string | null; planName: string; amountCents: number; currency: string };
type StripeElement = { mount(target: HTMLElement): void; unmount(): void; on(event: "ready", handler: () => void): void };
type StripeElements = { create(type: "payment"): StripeElement };
type StripeClient = { elements(options: { clientSecret: string; appearance?: Record<string, unknown> }): StripeElements; confirmPayment(options: { elements: StripeElements; redirect: "if_required"; confirmParams: { receipt_email: string } }): Promise<{ error?: { message?: string } }> };
const STORAGE_KEY = "ringo-membership-checkout";
const money = (cents: number, currency: string) => new Intl.NumberFormat(undefined, { style: "currency", currency }).format(cents / 100);
const stripeFactory = () => (window as unknown as { Stripe?: (key: string, options?: { stripeAccount?: string }) => StripeClient }).Stripe;
const benefits = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];

export default function MembershipPage() {
  const [config, setConfig] = useState<Config | null>(null); const [planId, setPlanId] = useState(""); const [memberName, setMemberName] = useState(""); const [memberEmail, setMemberEmail] = useState("");
  const [checkout, setCheckout] = useState<Checkout | null>(null); const [confirmation, setConfirmation] = useState<Confirmation | null>(null); const [elements, setElements] = useState<StripeElements | null>(null); const [paymentReady, setPaymentReady] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  const paymentRef = useRef<HTMLDivElement>(null); const checkoutKey = useRef<string | null>(null); const resumeAttempted = useRef(false);
  useEffect(() => { apiFetch<Config>("/membership-checkouts/config").then((value) => { setConfig(value); setPlanId(value.plans[0]?.id ?? ""); }).catch(() => setError("Membership enrollment is temporarily unavailable.")); }, []);
  useEffect(() => { if (!elements || !paymentRef.current) return; const element = elements.create("payment"); element.on("ready", () => setPaymentReady(true)); element.mount(paymentRef.current); return () => element.unmount(); }, [elements]);
  useEffect(() => { if (!config || resumeAttempted.current) return; resumeAttempted.current = true; const key = sessionStorage.getItem(STORAGE_KEY); if (!key) return; checkoutKey.current = key; setPending(true); apiFetch<Checkout>("/membership-checkouts/resume", { method: "POST", headers: { "Idempotency-Key": key }, body: "{}" }).then(async (resumed) => { setMemberName(resumed.memberName); setMemberEmail(resumed.memberEmail); if (resumed.payment.status === "SUCCEEDED") { setConfirmation(await apiFetch<Confirmation>(`/membership-checkouts/${resumed.checkoutId}/finalize`, { method: "POST", headers: { "Idempotency-Key": key }, body: "{}" })); sessionStorage.removeItem(STORAGE_KEY); return; } if (!resumed.payment.clientSecret) throw new Error("A secure payment session could not be resumed."); await mountPayment(resumed, config); }).catch((reason) => { if (reason instanceof ApiRequestError && reason.status === 404) { sessionStorage.removeItem(STORAGE_KEY); checkoutKey.current = null; } setError(failure(reason)); }).finally(() => setPending(false)); }, [config]);
  const failure = (reason: unknown) => reason instanceof ApiRequestError ? reason.body.message : reason instanceof Error ? reason.message : "The request could not be completed.";
  async function mountPayment(value: Checkout, settings: Config) { await loadStripeScript(); const factory = stripeFactory(); if (!factory || !settings.payment.publishableKey) throw new Error("Stripe payments are not configured."); setCheckout(value); setElements(factory(settings.payment.publishableKey, { stripeAccount: settings.payment.connectedAccountId ?? undefined }).elements({ clientSecret: value.payment.clientSecret!, appearance: { theme: "night" } })); }
  function resetCheckout() { checkoutKey.current = null; sessionStorage.removeItem(STORAGE_KEY); }
  function changePlan(value: string) { resetCheckout(); setPlanId(value); }
  async function start(event: FormEvent) { event.preventDefault(); if (!config || pending) return; setPending(true); setError(""); try { checkoutKey.current ||= crypto.randomUUID(); sessionStorage.setItem(STORAGE_KEY, checkoutKey.current); const created = await apiFetch<Checkout>("/membership-checkouts", { method: "POST", headers: { "Idempotency-Key": checkoutKey.current }, body: JSON.stringify({ locationId: config.locationId, planId, memberName, memberEmail }) }); if (!created.payment.clientSecret) throw new Error("A secure payment session could not be created."); await mountPayment(created, config); } catch (reason) { setError(failure(reason)); } finally { setPending(false); } }
  async function pay(event: FormEvent) { event.preventDefault(); const factory = stripeFactory(); if (!checkout || !elements || !factory || !config?.payment.publishableKey || pending) return; setPending(true); setError(""); try { const result = await factory(config.payment.publishableKey, { stripeAccount: config.payment.connectedAccountId ?? undefined }).confirmPayment({ elements, redirect: "if_required", confirmParams: { receipt_email: memberEmail } }); if (result.error) throw new Error(result.error.message ?? "Payment was declined."); setConfirmation(await apiFetch<Confirmation>(`/membership-checkouts/${checkout.checkoutId}/finalize`, { method: "POST", headers: { "Idempotency-Key": checkoutKey.current! }, body: "{}" })); sessionStorage.removeItem(STORAGE_KEY); } catch (reason) { setError(failure(reason)); } finally { setPending(false); } }
  const selected = config?.plans.find((plan) => plan.id === planId);
  return <main className="cinema-shell route-page"><section className="route-heading"><span className="eyebrow">MEMBERSHIP</span><h1>Join the cinema</h1><p>Support independent film and enjoy year-round member benefits.</p></section>{confirmation ? <section className="content-panel"><h2>Welcome</h2><p>Your {confirmation.planName} membership is active. A confirmation has been sent to {memberEmail}.</p><p>Member number: <strong>{confirmation.membershipNumber}</strong></p>{confirmation.expiresAt && <p>Valid through {new Date(confirmation.expiresAt).toLocaleDateString()}</p>}</section> : !checkout ? <form className="private-event-form content-panel" onSubmit={start}><h2>Choose a plan</h2>{config?.plans.length ? <><label>Membership plan<select required value={planId} onChange={(event) => changePlan(event.target.value)}>{config.plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} — {money(plan.priceCents, config.currency)}</option>)}</select></label>{selected && <div><p>{selected.description}</p><p>{selected.durationMonths} month{selected.durationMonths === 1 ? "" : "s"}</p>{benefits(selected.benefits).length > 0 && <ul>{benefits(selected.benefits).map((benefit) => <li key={benefit}>{benefit}</li>)}</ul>}</div>}<label>Name<input required maxLength={120} value={memberName} onChange={(event) => { resetCheckout(); setMemberName(event.target.value); }} /></label><label>Email<input type="email" required value={memberEmail} onChange={(event) => { resetCheckout(); setMemberEmail(event.target.value); }} /></label><button className="primary" disabled={pending || !config.payment.ready}>{pending ? "Preparing checkout…" : "Continue to secure payment"}</button></> : <p>No membership plans are currently available.</p>}</form> : <form className="content-panel" onSubmit={pay}><h2>Secure payment</h2><p>{checkout.planName} — {money(checkout.amountCents, checkout.currency)}</p><div ref={paymentRef} /><button className="primary" disabled={pending || !paymentReady}>{pending ? "Activating membership…" : `Join for ${money(checkout.amountCents, checkout.currency)}`}</button></form>}{error && <p className="error-banner">{error}</p>}</main>;
}
